name = "limeskey-com"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_date = "2026-03-31"
compatibility_flags = [ "nodejs_compat", "enable_nodejs_http_modules" ]

[vars]
NODE_VERSION = "25.8.2"
PNPM_VERSION = "10.33.0"

[env.production]
[env.production.vars]
NODE_VERSION = "25.8.2"
PNPM_VERSION = "10.33.0"

[env.preview]
[env.preview.vars]
NODE_VERSION = "25.8.2"
PNPM_VERSION = "10.33.0"